---
# Template configuration files for ibmcloud

- name: Set SELinux booleans
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    persistent: "{{ item.persistent | default('false') }}"
  loop: "{{ ibmcloud_selinux_booleans }}"
  when:
    - ansible_selinux.status == "enabled"
    - ibmcloud_enable_selinux
  become: true
