---
# Template configuration files for ibmcloud

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ ibmcloud_templates_copy }}"
  when: ibmcloud_copy_templates
